title: Luna Zea
description: Computational Biologist â€” interpreting the living world through data-driven insight.
baseurl: ""
url: "https://red-moonx.github.io"

email: luna.zea@example.com
github_username: red-moonx
linkedin_username: lunazea